"""
LandXML 1.2 builder.

Assembles horizontal + vertical geometry and cant data into a LandXML file
whose structure mirrors the layout expected by COYPU (GeoTEL Rail-style
export): coordinate points as child elements (<Start>/<PI>/<Center>/<End>),
spirals with desc/constant attributes, and a <Cant> block with one
<CantStation> per element boundary.

Cant values are exported as 0 mm placeholders — cant cannot be derived from
OSM data and is expected to be determined in downstream software (COYPU).
"""

import math
from datetime import datetime, timezone
from lxml import etree

LANDXML_NS = "http://www.landxml.org/schema/LandXML-1.2"
XSD_LOC = (
    "http://www.landxml.org/schema/LandXML-1.2 "
    "http://www.landxml.org/schema/LandXML-1.2/LandXML-1.2.xsd"
)

NUM_FMT   = "{:.6f}"          # 6 decimals everywhere, like the COYPU sample
COORD_FMT = "{:.6f}"

APP_NAME    = "COYPU Feeder"
APP_VERSION = "1.0.0"
APP_URL     = "https://github.com/surovskyjk/COYPU-Feeder"

DISCLAIMER = (
    "Generated by COYPU Feeder from OpenStreetMap data "
    "(© OpenStreetMap contributors, ODbL). The horizontal and vertical "
    "geometry is fitted from crowd-sourced survey data and is NOT a "
    "surveyed or design alignment — verify before any engineering use. "
    "Cant values are 0 mm placeholders to be determined in downstream "
    "software."
)

# Cant defaults (standard-gauge railway, values mirrored from COYPU sample)
CANT_GAUGE               = 1.435
CANT_SUPERELEVATION_BASE = 1.500
CANT_ROTATION_POINT      = "insideRail"


def build_landxml(
    alignments: list[dict],
    output_epsg: int,
    project_name: str = "Railway Alignment",
    force_positive: bool = False,
) -> etree._Element:
    """
    Build a LandXML 1.2 root element (COYPU-compatible structure).

    force_positive: if True, coordinate signs were stripped (abs applied)
                    before reaching this function — noted in Project desc.
    """
    XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"
    nsmap = {None: LANDXML_NS, "xsi": XSI_NS}
    root = etree.Element("LandXML", nsmap=nsmap)
    root.set("version", "1.2")
    root.set(f"{{{XSI_NS}}}schemaLocation", XSD_LOC)
    now = datetime.now(timezone.utc)
    root.set("date", now.strftime("%Y-%m-%d"))
    root.set("time", now.strftime("%H:%M:%S"))
    root.set("readOnly", "false")
    root.set("language", "English")

    app_el = etree.SubElement(root, "Application")
    app_el.set("name", APP_NAME)
    app_el.set("version", APP_VERSION)
    app_el.set("manufacturer", "COYPU Feeder (open-source OSM to LandXML converter)")
    app_el.set("manufacturerURL", APP_URL)
    author_el = etree.SubElement(app_el, "Author")
    author_el.set("createdBy", "COYPU Feeder — automated export based on OpenStreetMap")

    proj_el = etree.SubElement(root, "Project")
    proj_el.set("name", project_name)
    desc = DISCLAIMER
    if force_positive:
        desc += (
            f" Coordinates exported as absolute values (signs stripped) "
            f"for EPSG:{output_epsg} — numeric values are unchanged."
        )
    proj_el.set("desc", desc)

    units_el = etree.SubElement(root, "Units")
    metric_el = etree.SubElement(units_el, "Metric")
    metric_el.set("areaUnit", "squareMeter")
    metric_el.set("linearUnit", "meter")
    metric_el.set("volumeUnit", "cubicMeter")
    metric_el.set("temperatureUnit", "celsius")
    metric_el.set("pressureUnit", "HPA")

    cs_el = etree.SubElement(root, "CoordinateSystem")
    cs_el.set("epsgCode", str(output_epsg))
    cs_el.set("desc", f"EPSG:{output_epsg}")

    aligns_el = etree.SubElement(root, "Alignments")
    aligns_el.set("name", "alignments")
    for aln in alignments:
        _add_alignment(aligns_el, aln)

    return root


def write_landxml(root: etree._Element, filepath: str) -> None:
    tree = etree.ElementTree(root)
    tree.write(filepath, xml_declaration=True, encoding="UTF-8", pretty_print=True)


# ---------------------------------------------------------------------------
# Alignment
# ---------------------------------------------------------------------------

def _add_alignment(parent: etree._Element, aln: dict) -> None:
    elements = aln.get("elements", [])
    vertical = aln.get("vertical", [])
    sta_start = float(aln.get("sta_start", 0.0))
    total_length = sum(el.get("length", 0.0) for el in elements)

    el = etree.SubElement(parent, "Alignment")
    el.set("name", aln["name"])
    el.set("length", NUM_FMT.format(total_length))
    el.set("staStart", NUM_FMT.format(sta_start))

    coord_geom = etree.SubElement(el, "CoordGeom")
    for geom_el in elements:
        _add_geom_element(coord_geom, geom_el)

    if vertical:
        profile_el = etree.SubElement(el, "Profile")
        profile_el.set("staStart", NUM_FMT.format(sta_start))
        prof_align = etree.SubElement(profile_el, "ProfAlign")
        prof_align.set("name", aln["name"])
        _add_vertical_elements(prof_align, vertical)

    _add_cant(el, aln["name"], elements, sta_start)


# ---------------------------------------------------------------------------
# Horizontal elements
# ---------------------------------------------------------------------------

def _add_geom_element(parent: etree._Element, el: dict) -> None:
    etype = el.get("type")
    if etype == "Line":
        _add_line(parent, el)
    elif etype == "Arc":
        _add_curve(parent, el)
    elif etype == "Spiral":
        _add_spiral(parent, el)


def _add_line(parent: etree._Element, el: dict) -> None:
    line = etree.SubElement(parent, "Line")
    line.set("staStart", NUM_FMT.format(float(el.get("sta_start", 0.0))))
    _add_point(line, "Start", el["start"])
    _add_point(line, "End", el["end"])


def _add_curve(parent: etree._Element, el: dict) -> None:
    curve = etree.SubElement(parent, "Curve")
    curve.set("staStart", NUM_FMT.format(float(el.get("sta_start", 0.0))))
    curve.set("rot", el.get("rot", "ccw"))
    curve.set("crvType", "arc")
    curve.set("radius", NUM_FMT.format(el["radius"]))
    _add_point(curve, "Start", el["start"])
    if el.get("center"):
        _add_point(curve, "Center", el["center"])
    _add_point(curve, "End", el["end"])


def _add_spiral(parent: etree._Element, el: dict) -> None:
    r_start = float(el.get("radius_start", float("inf")))
    r_end   = float(el.get("radius_end",   float("inf")))
    is_entry = math.isinf(r_start) and not math.isinf(r_end)

    spiral = etree.SubElement(parent, "Spiral")
    spiral.set("staStart", NUM_FMT.format(float(el.get("sta_start", 0.0))))
    spiral.set("desc", "TangentToCurve" if is_entry else "CurveToTangent")
    spiral.set("length", NUM_FMT.format(el["length"]))
    spiral.set("radiusStart", "INF" if math.isinf(r_start) else NUM_FMT.format(r_start))
    spiral.set("radiusEnd",   "INF" if math.isinf(r_end)   else NUM_FMT.format(r_end))
    spiral.set("rot", el.get("rot", "ccw"))
    spiral.set("spiType", "clothoid")
    a = float(el.get("clothoid_A", 0.0))
    if a <= 0.0:
        r_fin = min((r for r in (r_start, r_end) if not math.isinf(r)), default=0.0)
        a = math.sqrt(max(0.0, r_fin * float(el["length"])))
    spiral.set("constant", NUM_FMT.format(a))

    _add_point(spiral, "Start", el["start"])
    pi = _spiral_pi(el, r_start, r_end)
    if pi is not None:
        _add_point(spiral, "PI", pi)
    _add_point(spiral, "End", el["end"])


def _spiral_pi(el: dict, r_start: float, r_end: float) -> list[float] | None:
    """
    Point of Intersection of the spiral's start and end tangents.

    Tangent headings from the chord using the clothoid chord relations
    (α ≈ θs/3 = L/(6R)):
      entry (∞→R): h_start = chord − sign·L/(6R), h_end = chord + sign·L/(3R)
      exit  (R→∞): h_start = chord − sign·L/(3R), h_end = chord + sign·L/(6R)
    """
    try:
        sx, sy = float(el["start"][0]), float(el["start"][1])
        ex, ey = float(el["end"][0]),   float(el["end"][1])
        L = float(el.get("length", 0.0))
        R = min((r for r in (r_start, r_end) if not math.isinf(r)), default=0.0)
        if L <= 0.0 or R <= 0.0:
            return None
        chord = math.atan2(ey - sy, ex - sx)
        sign  = 1.0 if el.get("rot", "ccw") == "ccw" else -1.0
        if math.isinf(r_start):                       # entry spiral
            h_start = chord - sign * L / (6.0 * R)
            h_end   = chord + sign * L / (3.0 * R)
        else:                                         # exit spiral
            h_start = chord - sign * L / (3.0 * R)
            h_end   = chord + sign * L / (6.0 * R)
        det = math.sin(h_end - h_start)
        if abs(det) < 1e-12:
            return [(sx + ex) / 2.0, (sy + ey) / 2.0]
        dx, dy = ex - sx, ey - sy
        t = (dx * math.sin(h_end) - dy * math.cos(h_end)) / det
        return [sx + t * math.cos(h_start), sy + t * math.sin(h_start)]
    except Exception:
        return None


def _add_point(parent: etree._Element, tag: str, xy: list[float]) -> None:
    pt = etree.SubElement(parent, tag)
    pt.text = f"{COORD_FMT.format(xy[1])} {COORD_FMT.format(xy[0])}"


# ---------------------------------------------------------------------------
# Vertical elements
# ---------------------------------------------------------------------------

def _add_vertical_elements(parent: etree._Element, vertical: list[dict]) -> None:
    for item in vertical:
        if item["type"] == "PVI":
            pvi = etree.SubElement(parent, "PVI")
            pvi.text = (
                f"{NUM_FMT.format(item['station'])} "
                f"{NUM_FMT.format(item['elevation'])}"
            )
        elif item["type"] == "ParaCurve":
            pc = etree.SubElement(parent, "ParaCurve")
            pc.set("length", NUM_FMT.format(item["length"]))
            pc.text = (
                f"{NUM_FMT.format(item['station'])} "
                f"{NUM_FMT.format(item['elevation'])}"
            )


# ---------------------------------------------------------------------------
# Cant
# ---------------------------------------------------------------------------

def _add_cant(parent: etree._Element, name: str, elements: list[dict],
              sta_start: float) -> None:
    """
    Emit a <Cant> block with one <CantStation> at every element boundary
    (start of each element plus the alignment end).

    All appliedCant values are 0 mm: cant cannot be derived from OSM data;
    it is expected to be designed in downstream software (COYPU).
    """
    if not elements:
        return

    cant = etree.SubElement(parent, "Cant")
    cant.set("name", name)
    cant.set("gauge", NUM_FMT.format(CANT_GAUGE))
    cant.set("superelevationBase", NUM_FMT.format(CANT_SUPERELEVATION_BASE))
    cant.set("rotationPoint", CANT_ROTATION_POINT)
    cant.set("coPlane", "false")
    cant.set("stationType", "centreline")

    # Element-boundary stations (deduplicated, ascending)
    stations: list[float] = []
    for el in elements:
        stations.append(float(el.get("sta_start", 0.0)))
    last = elements[-1]
    stations.append(float(last.get("sta_start", 0.0)) + float(last.get("length", 0.0)))
    dedup: list[float] = []
    for s in stations:
        if not dedup or abs(s - dedup[-1]) > 1e-6:
            dedup.append(s)

    for s in dedup:
        st = etree.SubElement(cant, "CantStation")
        st.set("station", NUM_FMT.format(s))
        st.set("appliedCant", NUM_FMT.format(0.0))
        st.set("rotationPoint", CANT_ROTATION_POINT)
        st.set("appliedGauge", NUM_FMT.format(CANT_GAUGE))
        st.set("appliedSuperelevation", NUM_FMT.format(CANT_SUPERELEVATION_BASE))
